spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cda_java}
    username: ${DB_USERNAME:cda}
    password: ${DB_PASSWORD:cda}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
  thymeleaf:
    cache: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: INFO
